### PR TITLE
recreate with vue 3

### PR DESCRIPTION
**Pull request by maexled**
Closes Gamify-IT/issues#124

- removed asyncs and awaits in crosswordgenerator.ts
- had to remove import env from config.ts - please adjust yourself @madebyTimo @Aaron2000119 

Also test if the rest communication still works!

### CODE REVIEW

**Comment by maexled** [comment]
Also if all works as expected check up the point `crosswordpuzzle works like before` in the linked issue

**Comment by madebyTimo** [comment]
There was the wrong backend url in the config.ts.
Also the question weren't shown if they are fetched from the backend.
grafik
I solved this by using Ref<> variables.

I also added a docker-compose to easily setup a development environment.

What do you think about my changes @maexled ?

**Comment by madebyTimo** [comment]
I also saw we are using localStorage to communicate between vue-components... very bad and also my bad cause I approved this in an older PR. But this is not part of this PR. I will create an issue

**Review by madebyTimo — APPROVED** [review]

**Comment by maexled** [comment]
Everything works fine. With the docker-compose it is much easier to test, thanks! I am also the opinion that it has to get a rework with communicating the current questions, storing in localstorage is not the best.

**Review by Aaron2000119 — APPROVED** [review]

**Comment by maexled** [comment]
One of you have to merge. I am not authorized to merge :(

**Comment by delvh** [comment]
You should have access now.

**Pull request merged**
